services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"  # Mapeia a porta 5432 do contêiner para a porta 5432 do host
    expose:
      - "5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tododb
    volumes:
      - db_data:/var/lib/postgresql  # Certifique-se de que o caminho está correto

volumes:
  db_data:  # Volume persistente para os dados
